NREL/hive

nrel/hive/app/hive_cosim.py, nrel/hive/app/run.py, nrel/hive/app/run_batch.py, nrel/hive/app/run_tune.py, nrel/hive/config/sim.py, nrel/hive/initialization/initialize_simulation.py, nrel/hive/initialization/load.py, nrel/hive/model/request/request.py, nrel/hive/runner/local_simulation_runner.py, nrel/hive/state/simulation_state/simulation_state.py, pyproject.toml, tests/test_initialize_simulation.py
Updates how we initialize a simulation to support injection of a custom road network at the highest level.
Now, an extension to the core library could call `run_sim()` and pass a set of custom initialization functions.
=> custom road network

nrel/hive/model/vehicle/mechatronics/bev.py, nrel/hive/model/vehicle/mechatronics/ice.py, nrel/hive/model/vehicle/mechatronics/powertrain/powertrain.py, nrel/hive/model/vehicle/mechatronics/powertrain/tabular_powertrain.py, nrel/hive/util/units.py
Updates the units in hive a bit to support more ways to represent units as strings. Now, units are converted from a string into an Unit enum. This was done to support some internal work to integrate routee powertrain.
=> make units an enum

examples/download_road_network.py, nrel/hive/initialization/initialize_simulation.py, nrel/hive/initialization/initialize_simulation_with_sampling.py, nrel/hive/model/roadnetwork/osm/osm_builders.py, nrel/hive/model/roadnetwork/osm/osm_road_network_link_helper.py, nrel/hive/model/roadnetwork/osm/osm_roadnetwork.py, nrel/hive/model/roadnetwork/roadnetwork.py, nrel/hive/resources/mock_lobster.py
In order to make building a new road network easier on the user, this adds a new `from_polygon` class method to the `OSMRoadNetwork` that uses osmnx and shapely on the backend to build a road network.
=> add from polygon method to OSMRoadNetwork

nrel/hive/model/roadnetwork/osm/osm_road_network_link_helper.py, nrel/hive/model/station/station.py, nrel/hive/state/simulation_state/update/step_simulation_ops.py, nrel/hive/state/vehicle_state/charging_station.py, nrel/hive/state/vehicle_state/dispatch_station.py, nrel/hive/state/vehicle_state/vehicle_state.py, tests/test_step_simulation_ops.py
Applies a couple of bug fixes discovered when creating a new hive scenario:
When transitioning out of dispatch station we were only going into charge queuing if the available chargers result was None. But, there were cases when this evaluated to 0. This has been updated such that the available chargers method only returns an integer and it gets properly checked.
I was running into some very strange behavior in which I would observe the vehicle stepping properly in the internal closure of the `perform_vehicle_state_updates` method, breaking [here](https://github.com/NREL/hive/blob/a0de4ecc07653adaa5bdef955c67eb2b09536b9f/nrel/hive/state/simulation_state/update/step_simulation_ops.py#L126) but then the change would not be reflected in the result …
=> fix charge queue bug

nrel/hive/initialization/initialize_simulation.py, nrel/hive/model/vehicle/mechatronics/__init__.py, nrel/hive/model/vehicle/mechatronics/bev.py, nrel/hive/model/vehicle/mechatronics/ice.py, nrel/hive/model/vehicle/mechatronics/powertrain/__init__.py, nrel/hive/model/vehicle/mechatronics/powertrain/powertrain.py
refactors how we initialize the environment to make it easier to inject custom powertrains; this will be used internally to use routee-powertrain to predict energy consumption.
=> add environment init functions

nrel/hive/app/run.py, nrel/hive/model/entity_position.py, nrel/hive/model/membership.py, nrel/hive/model/roadnetwork/haversine_roadnetwork.py, nrel/hive/model/roadnetwork/linktraversal.py, nrel/hive/resources/scenarios/denver_downtown/denver_demo.yaml, nrel/hive/util/rust.py, rust/Cargo.lock, rust/Cargo.toml, rust/src/entity_position.rs, rust/src/geoid.rs, rust/src/lib.rs, rust/src/link.rs, rust/src/road_network.rs, rust/src/utils.rs
Adds in a rust haversine road network (and associated data structures like entity position and link traversal). 
Also updates how to run with the rust entities using the `USE_RUST` environment variable:
```shell
USE_RUST=True hive denver_demo.yaml
```
=> Rust haversine road network

nrel/hive/app/hive_cosim.py, nrel/hive/config/global_config.py, nrel/hive/config/hive_config.py, nrel/hive/resources/defaults/.hive.yaml, nrel/hive/state/simulation_state/simulation_state_ops.py, nrel/hive/state/vehicle_state/servicing_ops.py, pyproject.toml
Applies a couple of things:
- upgrades to mypy 1 and fixes new errors
- when setting the scenario directory date in the function signature, we lose the ability to reset a scenario in the same python processes and have the date be updated. This moves the date setting to happen when the code is called and not just when it is initialized.
- adds a new `verbose` flag to the global config to optionally cut down on logging noise when programmatically running several scenarios back-to-back
=> upgrade to mypy 1; properly set scenario output dir; add verbose flag

nrel/hive/state/driver_state/human_driver_state/human_driver_state.py
Fixes a performance bug in which human drivers were continuing to issue instructions even when in uninterruptible states (like OutOfService and ServicingTrip). This just adds a check to make sure they don't issue instructions in those states.
=> don't issue human instruction on certain states

nrel/hive/app/hive_cosim.py, nrel/hive/dispatcher/instruction/instructions.py, nrel/hive/initialization/load.py, nrel/hive/state/simulation_state/update/step_simulation_ops.py, pyproject.toml
this quick PR exposes output_suffix via the cosim API so that the suffix can be set before creating the scenario.
in both cases where it has been added to a function signature, it has been done with a default value that is consistent with any existing invocations.
=> expose output_suffix in cosim API

nrel/hive/config/dispatcher_config.py, nrel/hive/resources/defaults/hive_config.yaml, nrel/hive/state/driver_state/driver_instruction_ops.py
Updates the human driver logic such that when they go off-shift, any driver that either cannot get home without running out of energy, or, does't have home charging will attempt to charge at the shift end to a new config parameter `config.distpacher.human_driver_off_shift_charge_target`
=> adjust human driver go home logic

pyproject.toml
quick change to address #139, preventing users from mistakenly installing the forthcoming uber h3 4.x series with breaking API changes. leaving the issue open for discussion + work to upgrade to the 4.x API.
=> restrict to h3 3.x

docs/source/conf.py, pyproject.toml
includes a missing and urgent update for running shortest path searches based on travel times, as well as documentation improvements. [commit log](https://github.com/NREL/hive/compare/v1.2.1...release-v1.2.2)
=> version 1.2.2

docs/source/developer/index.rst
Links in the contributing page to the developer section in the documentation
=> add contributing page to developers page on docs

.github/workflows/tests.yaml, README.md, pyproject.toml
In May of 2020, we added python 3.7 support since several of the reinforcement learning algorithms we were using did not yet support anything above 3.7. Since then the libraries like RLlib has been updated to support later versions of python. I think it makes sense to drop this now, opening us up to use 3.8 and up specific features.
=> pull out python 3.7 support

docs/source/developer/release.md
Found during discussion of https://github.com/NREL/hive/issues/168
During the Pycon sprint, found that a virtual environment that I'd run `pip install nrel.hive` in was executing code that had a bug that was fixed six months ago. On investigation, found that the wheel had had an old directory bundled into it, most likely from a desktop computer where the working directory hadn't been cleaned up between now and the creation of the `nrel` subdirectory.
```
unzip -l nrel.hive-1.2.2-py3-none-any.whl 
Archive:  nrel.hive-1.2.2-py3-none-any.whl
Length      Date    Time    Name
---------  ---------- -----   ----
6148  2023-02-07 23:38   .DS_Store
1428  2022-08-16 17:54   hive/__init__.py
94  2022-08-17 15:37   hive/__main__.py
(...)
56  2022-11-02 21:45   nrel/__init__.py
1327  2022-11-29 19:20 …
```
=> [#168] Correct build process docs to remove unwanted files first

docs/source/customize.md, docs/source/index.rst, docs/source/quick_start.md
Adds a new quick start section to the docs landing page. Also adds a customize page that starts to explain things like how to run a co-simulation and how to inject custom control logic.
=> add a quick start and customize page to docs

nrel/hive/model/base.py, rust/pyproject.toml, rust/src/base.rs, rust/src/entity_position.rs, rust/src/geoid.rs, rust/src/lib.rs, rust/src/link.rs, rust/src/membership.rs, rust/src/passenger.rs, rust/src/road_network.rs, rust/src/station.rs, rust/src/type_aliases.rs, rust/src/utils.rs
I pulled out the type aliases into a separate file (and added a bunch from `typealiases.py` that are unused so far). I also ran `cargo fmt`, which is the source of some of the random formatting changes.
Then I added a `Passenger` rust implementation. It was mostly straightforward, but internally it stores `SimTime` as a type aliased integer rather than custom implementing `SimTime` as a `#[pyclass]` extending `int`. Because the extra methods on `SimTime` are primarily for converting to/from human-readable formats this seems fine to me.
=> Passenger rust implementation

docs/source/customize.md, examples/cosim_custom_dispatcher.py, nrel/hive/dispatcher/instruction_generator/instruction_function.py, nrel/hive/initialization/load.py, tests/test_initialize_simulation.py
Closes #129 by adding the ability to specify custom control logic as either a `InstructionGenerator` or an `InstructionFunction` which is any callable that has the signature `Callable[[SimulationState, Environment], Tuple[Instruction, ...]]`
@robfitzgerald I'm interested to hear if this satisfies what you had in mind with #129
=> add ability to specify custom instruction generator function

.github/workflows/release_and_publish_pypi.yaml, .github/workflows/tests.yaml
Add a check if we're pulling in an approved PR so we don't re-run CI tests since they're required for getting the PR merged in the first place.
=> don't run duplicate tests on PR merge

.github/workflows/tests.yaml, .pre-commit-config.yaml, docs/source/developer/contributing.md, pyproject.toml
This adds pre-commit with the following tools:
- Defaults recommended by pre-commit (trailing newline, trailing whitespace, check yaml)
- Ruff
- Black
pre-commit only enforces checks on files changed as part of a commit unless running with `pre-commit run --all-files`. This means that the changes can be made gradually as individual files are changed.
Closes #178
=> add pre-commit setup

nrel/hive/model/base.py, tests/test_base.py, tests/test_kepler_feature.py
Fixes #112. This is the first PR that includes `pre-commit` linting and the import changes are a result of that (`ruff` can't analyze * imports, so they should be imported directly from the definition instead).
=> From row error

nrel/hive/config/hive_config.py, nrel/hive/model/roadnetwork/osm/osm_roadnetwork.py
Based on the networkx docs, the shortest path algorithm accepts a weight string and if that string does not appear on an edge, the weight defaults to 1. This makes sure that the travel time attribute exists on all the edges when importing a graph.  
Closes #36
=> make sure graph has travel time

nrel/hive/util/dict_ops.py
a quick fix. these error messages were observed for larger-running scenarios:
a combined filter + sort was being applied to a collection where it was assumed that the filter occurred before the sort. this behavior was swapped in the recent determinism refactor. this fix ensures filters are applied before the sorts, which should be the default behavior (downsampling the size of $n$ before applying a $O(n\ \log\ n)$ operation is more performant).
=> ensure filter occurs before sort
